USE CPSS
GO
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('QtyScale', 2)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('UnitPriceScale', 2)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('TotalScale', 2)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('DiscountRateScale', 0)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('TaxRate', 0)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('UseSameTaxRate', 1)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('UseSaleTrace', 1)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('UseBuyTrace', 1)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('SaleBuyPriceTrace', 1)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('UseRecentBuyPrice2CostPrice', 1)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('AutoGenerateBillNumber', 1)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('PrintAddCount', 1)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('NotModifyBillDate', 1)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('SNPrintStyle', 20)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('KeepOrignalInputMan', 1)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('RetailUsePos', 0)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('RetailCanMakeBalance', 0)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('ProductRepeatAlert', 0)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('CheckSNIsSell', 1)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('FilterZeroProduct', 1)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('LessThanStorageQtyAlert', 1)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('NotCheckSNForSave', 1)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('QuickInputDisplayWithRows', 0)
INSERT INTO dbo.sysconfig(configname,configvlaue) VALUES ('DataSelectPageSize', 30)