USE CPSS
GO
IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE id=OBJECT_ID(N'[dbo].[unit]') AND OBJECTPROPERTY(id,N'IsUserTable')=1)
BEGIN
	DROP TABLE [dbo].[unit]
END
GO
CREATE TABLE [dbo].[unit](
	[unitid] INT IDENTITY(1,1) NOT NULL,
	[name] VARCHAR(10) NOT NULL,
	[status] SMALLINT NOT NULL,
	[sort] INT NULL DEFAULT(0),
	[modifydate] TIMESTAMP NOT NULL,
 CONSTRAINT [PK_unit_unitid] PRIMARY KEY CLUSTERED 
(
	[unitid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 99) ON [PRIMARY]
) ON [PRIMARY]
GO