USE CPSS
GO
IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE id=OBJECT_ID(N'[dbo].[sysconfig]') AND OBJECTPROPERTY(id,N'IsUserTable')=1)
BEGIN
	DROP TABLE [dbo].[sysconfig]
END
GO
CREATE TABLE [dbo].[sysconfig](
	[configid] INT IDENTITY(1,1) NOT NULL,
	[configname] VARCHAR(50) NOT NULL,
	[configvlaue] INT NOT NULL,
 CONSTRAINT [PK_sysconfig_configid] PRIMARY KEY CLUSTERED 
(
	[configid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 99) ON [PRIMARY]
) ON [PRIMARY]
GO