//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;

namespace CPSS.Data.DataAccess
{
	/// <summary>
    /// 手动映射DataReader到AccountDataModel
    /// </summary>
    public partial class DataReaderToAccountDataModelMapper : IDataReaderToEntityMapper<CPSS.Data.DataAcess.DataModels.AccountDataModel>
    {
		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void Map(IDataReader dataReader, CPSS.Data.DataAcess.DataModels.AccountDataModel entity)
	    {            
            entity.account_id = (int)dataReader["account_id"];
            entity.class_id = (string)dataReader["class_id"];
            entity.parent_id = (string)dataReader["parent_id"];
            entity.child_number = (int)dataReader["child_number"];
            entity.child_count = (int)dataReader["child_count"];
            entity.name = (string)dataReader["name"];
            entity.deleted = (bool)dataReader["deleted"];
            entity.alias = (string)dataReader["alias"];
            entity.serial_number = (string)dataReader["serial_number"];
            entity.Comment = (string)dataReader["Comment"];
            entity.cur_total = (System.Decimal)dataReader["cur_total"];
            entity.ini_total = (System.Decimal)dataReader["ini_total"];
            entity.sysflag = (string)dataReader["sysflag"];
            entity.sysrow = (bool)dataReader["sysrow"];
            entity.PinYin = (string)dataReader["PinYin"];
            entity.total_01 = (System.Decimal)dataReader["total_01"];
            entity.total_02 = (System.Decimal)dataReader["total_02"];
            entity.total_03 = (System.Decimal)dataReader["total_03"];
            entity.total_04 = (System.Decimal)dataReader["total_04"];
            entity.total_05 = (System.Decimal)dataReader["total_05"];
            entity.total_06 = (System.Decimal)dataReader["total_06"];
            entity.total_07 = (System.Decimal)dataReader["total_07"];
            entity.total_08 = (System.Decimal)dataReader["total_08"];
            entity.total_09 = (System.Decimal)dataReader["total_09"];
            entity.total_10 = (System.Decimal)dataReader["total_10"];
            entity.total_11 = (System.Decimal)dataReader["total_11"];
            entity.total_12 = (System.Decimal)dataReader["total_12"];
            entity.bqtotal = (System.Decimal)dataReader["bqtotal"];
            entity.sumtotal = (System.Decimal)dataReader["sumtotal"];
            entity.cashaudit = (bool)dataReader["cashaudit"];
            entity.direction = (bool)dataReader["direction"];
            entity.ModifyDate = (System.Byte[])dataReader["ModifyDate"];
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public CPSS.Data.DataAcess.DataModels.AccountDataModel Map(IDataReader dataReader)
	    {
			var result = new CPSS.Data.DataAcess.DataModels.AccountDataModel();
            result.account_id = (int)dataReader["account_id"];
            result.class_id = (string)dataReader["class_id"];
            result.parent_id = (string)dataReader["parent_id"];
            result.child_number = (int)dataReader["child_number"];
            result.child_count = (int)dataReader["child_count"];
            result.name = (string)dataReader["name"];
            result.deleted = (bool)dataReader["deleted"];
            result.alias = (string)dataReader["alias"];
            result.serial_number = (string)dataReader["serial_number"];
            result.Comment = (string)dataReader["Comment"];
            result.cur_total = (System.Decimal)dataReader["cur_total"];
            result.ini_total = (System.Decimal)dataReader["ini_total"];
            result.sysflag = (string)dataReader["sysflag"];
            result.sysrow = (bool)dataReader["sysrow"];
            result.PinYin = (string)dataReader["PinYin"];
            result.total_01 = (System.Decimal)dataReader["total_01"];
            result.total_02 = (System.Decimal)dataReader["total_02"];
            result.total_03 = (System.Decimal)dataReader["total_03"];
            result.total_04 = (System.Decimal)dataReader["total_04"];
            result.total_05 = (System.Decimal)dataReader["total_05"];
            result.total_06 = (System.Decimal)dataReader["total_06"];
            result.total_07 = (System.Decimal)dataReader["total_07"];
            result.total_08 = (System.Decimal)dataReader["total_08"];
            result.total_09 = (System.Decimal)dataReader["total_09"];
            result.total_10 = (System.Decimal)dataReader["total_10"];
            result.total_11 = (System.Decimal)dataReader["total_11"];
            result.total_12 = (System.Decimal)dataReader["total_12"];
            result.bqtotal = (System.Decimal)dataReader["bqtotal"];
            result.sumtotal = (System.Decimal)dataReader["sumtotal"];
            result.cashaudit = (bool)dataReader["cashaudit"];
            result.direction = (bool)dataReader["direction"];
            result.ModifyDate = (System.Byte[])dataReader["ModifyDate"];
			return result;
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void MapObject(IDataReader dataReader, object entity)
	    {
	        this.Map(dataReader, entity as CPSS.Data.DataAcess.DataModels.AccountDataModel);
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public object MapObject(IDataReader dataReader)
	    {
	        return this.Map(dataReader);
	    }
	}
}
