//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;

namespace CPSS.Data.DataAccess
{
	/// <summary>
    /// 手动映射DataReader到CompanyInfoDataModel
    /// </summary>
    public partial class DataReaderToCompanyInfoDataModelMapper
    {
		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void Map(IDataReader dataReader, CPSS.Data.DataAcess.DataModels.User.CompanyInfoDataModel entity)
	    {            
            entity.comid = (int)dataReader["CompanyID"];
            entity.dbserver = (string)dataReader["Server"];
            entity.dbase = (string)dataReader["Database"];
            entity.timeout = (int)dataReader["ConnectTimeout"];
            entity.uid = (string)dataReader["UserID"];
            entity.pwd = (string)dataReader["Password"];
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public CPSS.Data.DataAcess.DataModels.User.CompanyInfoDataModel Map(IDataReader dataReader)
	    {
			var result = new CPSS.Data.DataAcess.DataModels.User.CompanyInfoDataModel();
            result.comid = (int)dataReader["CompanyID"];
            result.dbserver = (string)dataReader["Server"];
            result.dbase = (string)dataReader["Database"];
            result.timeout = (int)dataReader["ConnectTimeout"];
            result.uid = (string)dataReader["UserID"];
            result.pwd = (string)dataReader["Password"];
			return result;
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void MapObject(IDataReader dataReader, object entity)
	    {
	        this.Map(dataReader, entity as CPSS.Data.DataAcess.DataModels.User.CompanyInfoDataModel);
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public object MapObject(IDataReader dataReader)
	    {
	        return this.Map(dataReader);
	    }
	}
}
