//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;

namespace CPSS.Data.DataAccess
{
	/// <summary>
    /// 手动映射DataReader到DepartmentDataModel
    /// </summary>
    public partial class DataReaderToDepartmentDataModelMapper : IDataReaderToEntityMapper<CPSS.Data.DataAcess.DataModels.DepartmentDataModel>
    {
		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void Map(IDataReader dataReader, CPSS.Data.DataAcess.DataModels.DepartmentDataModel entity)
	    {            
            entity.department_Id = (int)dataReader["department_Id"];
            entity.class_id = (string)dataReader["class_id"];
            entity.parent_id = (string)dataReader["parent_id"];
            entity.child_number = (int)dataReader["child_number"];
            entity.child_count = (int)dataReader["child_count"];
            entity.serial_number = (string)dataReader["serial_number"];
            entity.name = (string)dataReader["name"];
            entity.comment = (string)dataReader["comment"];
            entity.deleted = (bool)dataReader["deleted"];
            entity.ModifyDate = (System.Byte[])dataReader["ModifyDate"];
            entity.pinyin = (string)dataReader["pinyin"];
            entity.Flag = (bool)dataReader["Flag"];
            entity.RowIndex = (int)dataReader["RowIndex"];
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public CPSS.Data.DataAcess.DataModels.DepartmentDataModel Map(IDataReader dataReader)
	    {
			var result = new CPSS.Data.DataAcess.DataModels.DepartmentDataModel();
            result.department_Id = (int)dataReader["department_Id"];
            result.class_id = (string)dataReader["class_id"];
            result.parent_id = (string)dataReader["parent_id"];
            result.child_number = (int)dataReader["child_number"];
            result.child_count = (int)dataReader["child_count"];
            result.serial_number = (string)dataReader["serial_number"];
            result.name = (string)dataReader["name"];
            result.comment = (string)dataReader["comment"];
            result.deleted = (bool)dataReader["deleted"];
            result.ModifyDate = (System.Byte[])dataReader["ModifyDate"];
            result.pinyin = (string)dataReader["pinyin"];
            result.Flag = (bool)dataReader["Flag"];
            result.RowIndex = (int)dataReader["RowIndex"];
			return result;
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void MapObject(IDataReader dataReader, object entity)
	    {
	        this.Map(dataReader, entity as CPSS.Data.DataAcess.DataModels.DepartmentDataModel);
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public object MapObject(IDataReader dataReader)
	    {
	        return this.Map(dataReader);
	    }
	}
}
