//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;

namespace CPSS.Data.DataAccess
{
	/// <summary>
    /// 手动映射DataReader到employeeDataModel
    /// </summary>
    public partial class DataReaderToemployeeDataModelMapper
    {
		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void Map(IDataReader dataReader, CPSS.Data.DataAcess.DataModels.employeeDataModel entity)
	    {            
            entity.empid = (int)dataReader["empid"];
            entity.classid = (string)dataReader["classid"];
            entity.parentid = (string)dataReader["parentid"];
            entity.childnumber = (int)dataReader["childnumber"];
            entity.serialnumber = (string)dataReader["serialnumber"];
            entity.name = (string)dataReader["name"];
            entity.pinyin = (string)dataReader["pinyin"];
            entity.depid = (int)dataReader["depid"];
            entity.depname = (string)dataReader["depname"];
            entity.lowestdiscount = dataReader.IsDBNull(dataReader.GetOrdinal("lowestdiscount"))? null: (System.Nullable<short>)dataReader["lowestdiscount"];
            entity.preinadvancetotal = dataReader.IsDBNull(dataReader.GetOrdinal("preinadvancetotal"))? null: (System.Nullable<System.Decimal>)dataReader["preinadvancetotal"];
            entity.prepayfeetotal = dataReader.IsDBNull(dataReader.GetOrdinal("prepayfeetotal"))? null: (System.Nullable<System.Decimal>)dataReader["prepayfeetotal"];
            entity.mobile = (string)dataReader["mobile"];
            entity.address = (string)dataReader["address"];
            entity.status = dataReader.IsDBNull(dataReader.GetOrdinal("status"))? null: (System.Nullable<short>)dataReader["status"];
            entity.deleted = dataReader.IsDBNull(dataReader.GetOrdinal("deleted"))? null: (System.Nullable<short>)dataReader["deleted"];
            entity.sort = dataReader.IsDBNull(dataReader.GetOrdinal("sort"))? null: (int?)dataReader["sort"];
            entity.comment = (string)dataReader["comment"];
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public CPSS.Data.DataAcess.DataModels.employeeDataModel Map(IDataReader dataReader)
	    {
			var result = new CPSS.Data.DataAcess.DataModels.employeeDataModel();
            result.empid = (int)dataReader["empid"];
            result.classid = (string)dataReader["classid"];
            result.parentid = (string)dataReader["parentid"];
            result.childnumber = (int)dataReader["childnumber"];
            result.serialnumber = (string)dataReader["serialnumber"];
            result.name = (string)dataReader["name"];
            result.pinyin = (string)dataReader["pinyin"];
            result.depid = (int)dataReader["depid"];
            result.depname = (string)dataReader["depname"];
			result.lowestdiscount = dataReader.IsDBNull(dataReader.GetOrdinal("lowestdiscount"))? null: (System.Nullable<short>)dataReader["lowestdiscount"];
			result.preinadvancetotal = dataReader.IsDBNull(dataReader.GetOrdinal("preinadvancetotal"))? null: (System.Nullable<System.Decimal>)dataReader["preinadvancetotal"];
			result.prepayfeetotal = dataReader.IsDBNull(dataReader.GetOrdinal("prepayfeetotal"))? null: (System.Nullable<System.Decimal>)dataReader["prepayfeetotal"];
            result.mobile = (string)dataReader["mobile"];
            result.address = (string)dataReader["address"];
			result.status = dataReader.IsDBNull(dataReader.GetOrdinal("status"))? null: (System.Nullable<short>)dataReader["status"];
			result.deleted = dataReader.IsDBNull(dataReader.GetOrdinal("deleted"))? null: (System.Nullable<short>)dataReader["deleted"];
			result.sort = dataReader.IsDBNull(dataReader.GetOrdinal("sort"))? null: (int?)dataReader["sort"];
            result.comment = (string)dataReader["comment"];
			return result;
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void MapObject(IDataReader dataReader, object entity)
	    {
	        this.Map(dataReader, entity as CPSS.Data.DataAcess.DataModels.employeeDataModel);
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public object MapObject(IDataReader dataReader)
	    {
	        return this.Map(dataReader);
	    }
	}
}
