//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;

namespace CPSS.Data.DataAccess
{
	/// <summary>
    /// 手动映射DataReader到Entities
    /// </summary>
    public partial class DataReaderToEntitiesMapper : IDataReaderToEntityMapper<CPSS.Data.DataAcess.DataModels.Entities>
    {
		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void Map(IDataReader dataReader, CPSS.Data.DataAcess.DataModels.Entities entity)
	    {            
            entity.Account = (System.Data.Entity.DbSet<CPSS.Data.DataAcess.DataModels.AccountDataModel>)dataReader["Account"];
            entity.Clients = (System.Data.Entity.DbSet<CPSS.Data.DataAcess.DataModels.ClientsDataModel>)dataReader["Clients"];
            entity.Company = (System.Data.Entity.DbSet<CPSS.Data.DataAcess.DataModels.CompanyDataModel>)dataReader["Company"];
            entity.Department = (System.Data.Entity.DbSet<CPSS.Data.DataAcess.DataModels.DepartmentDataModel>)dataReader["Department"];
            entity.Employees = (System.Data.Entity.DbSet<CPSS.Data.DataAcess.DataModels.EmployeesDataModel>)dataReader["Employees"];
            entity.Database = (System.Data.Entity.Database)dataReader["Database"];
            entity.ChangeTracker = (System.Data.Entity.Infrastructure.DbChangeTracker)dataReader["ChangeTracker"];
            entity.Configuration = (System.Data.Entity.Infrastructure.DbContextConfiguration)dataReader["Configuration"];
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public CPSS.Data.DataAcess.DataModels.Entities Map(IDataReader dataReader)
	    {
			var result = new CPSS.Data.DataAcess.DataModels.Entities();
            result.Account = (System.Data.Entity.DbSet<CPSS.Data.DataAcess.DataModels.AccountDataModel>)dataReader["Account"];
            result.Clients = (System.Data.Entity.DbSet<CPSS.Data.DataAcess.DataModels.ClientsDataModel>)dataReader["Clients"];
            result.Company = (System.Data.Entity.DbSet<CPSS.Data.DataAcess.DataModels.CompanyDataModel>)dataReader["Company"];
            result.Department = (System.Data.Entity.DbSet<CPSS.Data.DataAcess.DataModels.DepartmentDataModel>)dataReader["Department"];
            result.Employees = (System.Data.Entity.DbSet<CPSS.Data.DataAcess.DataModels.EmployeesDataModel>)dataReader["Employees"];
            result.Database = (System.Data.Entity.Database)dataReader["Database"];
            result.ChangeTracker = (System.Data.Entity.Infrastructure.DbChangeTracker)dataReader["ChangeTracker"];
            result.Configuration = (System.Data.Entity.Infrastructure.DbContextConfiguration)dataReader["Configuration"];
			return result;
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void MapObject(IDataReader dataReader, object entity)
	    {
	        this.Map(dataReader, entity as CPSS.Data.DataAcess.DataModels.Entities);
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public object MapObject(IDataReader dataReader)
	    {
	        return this.Map(dataReader);
	    }
	}
}
