//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;

namespace CPSS.Data.DataAccess
{
	/// <summary>
    /// 手动映射DataReader到HeadButtonsDataModel
    /// </summary>
    public partial class DataReaderToHeadButtonsDataModelMapper
    {
		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void Map(IDataReader dataReader, CPSS.Data.DataAcess.DataModels.HeadButtons.HeadButtonsDataModel entity)
	    {            
            entity.ButtonText = (string)dataReader["ButtonText"];
            entity.ButtonName = (string)dataReader["ButtonName"];
            entity.ButtonDisabled = (bool)dataReader["ButtonDisabled"];
            entity.ButtonIconCls = (string)dataReader["ButtonIconCls"];
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public CPSS.Data.DataAcess.DataModels.HeadButtons.HeadButtonsDataModel Map(IDataReader dataReader)
	    {
			var result = new CPSS.Data.DataAcess.DataModels.HeadButtons.HeadButtonsDataModel();
            result.ButtonText = (string)dataReader["ButtonText"];
            result.ButtonName = (string)dataReader["ButtonName"];
            result.ButtonDisabled = (bool)dataReader["ButtonDisabled"];
            result.ButtonIconCls = (string)dataReader["ButtonIconCls"];
			return result;
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void MapObject(IDataReader dataReader, object entity)
	    {
	        this.Map(dataReader, entity as CPSS.Data.DataAcess.DataModels.HeadButtons.HeadButtonsDataModel);
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public object MapObject(IDataReader dataReader)
	    {
	        return this.Map(dataReader);
	    }
	}
}
