//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;

namespace CPSS.Data.DataAccess
{
	/// <summary>
    /// 手动映射DataReader到LeftNavMenuDataModel
    /// </summary>
    public partial class DataReaderToLeftNavMenuDataModelMapper
    {
		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void Map(IDataReader dataReader, CPSS.Data.DataAcess.DataModels.MainPage.LeftNavMenuDataModel entity)
	    {            
            entity.MenuID = (int)dataReader["MenuID"];
            entity.ClassID = (string)dataReader["ClassID"];
            entity.ParentClassID = (string)dataReader["ParentClassID"];
            entity.Title = (string)dataReader["Title"];
            entity.IconCls = (string)dataReader["IconCls"];
            entity.Url = (string)dataReader["Url"];
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public CPSS.Data.DataAcess.DataModels.MainPage.LeftNavMenuDataModel Map(IDataReader dataReader)
	    {
			var result = new CPSS.Data.DataAcess.DataModels.MainPage.LeftNavMenuDataModel();
            result.MenuID = (int)dataReader["MenuID"];
            result.ClassID = (string)dataReader["ClassID"];
            result.ParentClassID = (string)dataReader["ParentClassID"];
            result.Title = (string)dataReader["Title"];
            result.IconCls = (string)dataReader["IconCls"];
            result.Url = (string)dataReader["Url"];
			return result;
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void MapObject(IDataReader dataReader, object entity)
	    {
	        this.Map(dataReader, entity as CPSS.Data.DataAcess.DataModels.MainPage.LeftNavMenuDataModel);
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public object MapObject(IDataReader dataReader)
	    {
	        return this.Map(dataReader);
	    }
	}
}
