//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;

namespace CPSS.Data.DataAccess
{
	/// <summary>
    /// 手动映射DataReader到OnlineSigninUserDataModel
    /// </summary>
    public partial class DataReaderToOnlineSigninUserDataModelMapper
    {
		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void Map(IDataReader dataReader, CPSS.Data.DataAcess.DataModels.User.OnlineSigninUserDataModel entity)
	    {            
            entity.userid = (int)dataReader["userid"];
            entity.username = (string)dataReader["username"];
            entity.userip = (string)dataReader["userip"];
            entity.browser = (string)dataReader["browser"];
            entity.logintime = (DateTime)dataReader["logintime"];
            entity.overtime = (DateTime)dataReader["overtime"];
            entity.exptime = (DateTime)dataReader["exptime"];
            entity.sguid = (Guid)dataReader["sguid"];
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public CPSS.Data.DataAcess.DataModels.User.OnlineSigninUserDataModel Map(IDataReader dataReader)
	    {
			var result = new CPSS.Data.DataAcess.DataModels.User.OnlineSigninUserDataModel();
            result.userid = (int)dataReader["userid"];
            result.username = (string)dataReader["username"];
            result.userip = (string)dataReader["userip"];
            result.browser = (string)dataReader["browser"];
            result.logintime = (DateTime)dataReader["logintime"];
            result.overtime = (DateTime)dataReader["overtime"];
            result.exptime = (DateTime)dataReader["exptime"];
            result.sguid = (Guid)dataReader["sguid"];
			return result;
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void MapObject(IDataReader dataReader, object entity)
	    {
	        this.Map(dataReader, entity as CPSS.Data.DataAcess.DataModels.User.OnlineSigninUserDataModel);
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public object MapObject(IDataReader dataReader)
	    {
	        return this.Map(dataReader);
	    }
	}
}
