//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;

namespace CPSS.Data.DataAccess
{
	/// <summary>
    /// 手动映射DataReader到OnlineSigninUserDataModel
    /// </summary>
    public partial class DataReaderToOnlineSigninUserDataModelMapper
    {
		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void Map(IDataReader dataReader, CPSS.Data.DataAcess.DataModels.User.OnlineSigninUserDataModel entity)
	    {            
            entity.LoginName = (string)dataReader["LoginName"];
            entity.UserFrom = (string)dataReader["UserFrom"];
            entity.Browser = (string)dataReader["Browser"];
            entity.LoginTime = (DateTime)dataReader["LoginTime"];
            entity.OverTime = (DateTime)dataReader["OverTime"];
            entity.ExpTime = (DateTime)dataReader["ExpTime"];
            entity.SGuid = (Guid)dataReader["SGuid"];
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public CPSS.Data.DataAcess.DataModels.User.OnlineSigninUserDataModel Map(IDataReader dataReader)
	    {
			var result = new CPSS.Data.DataAcess.DataModels.User.OnlineSigninUserDataModel();
            result.LoginName = (string)dataReader["LoginName"];
            result.UserFrom = (string)dataReader["UserFrom"];
            result.Browser = (string)dataReader["Browser"];
            result.LoginTime = (DateTime)dataReader["LoginTime"];
            result.OverTime = (DateTime)dataReader["OverTime"];
            result.ExpTime = (DateTime)dataReader["ExpTime"];
            result.SGuid = (Guid)dataReader["SGuid"];
			return result;
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void MapObject(IDataReader dataReader, object entity)
	    {
	        this.Map(dataReader, entity as CPSS.Data.DataAcess.DataModels.User.OnlineSigninUserDataModel);
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public object MapObject(IDataReader dataReader)
	    {
	        return this.Map(dataReader);
	    }
	}
}
