//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;

namespace CPSS.Data.DataAccess
{
	/// <summary>
    /// 手动映射DataReader到SigninUserDataModel
    /// </summary>
    public partial class DataReaderToSigninUserDataModelMapper
    {
		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void Map(IDataReader dataReader, CPSS.Data.DataAcess.DataModels.User.SigninUserDataModel entity)
	    {            
            entity.UserID = (int)dataReader["UserID"];
            entity.UserName = (string)dataReader["UserName"];
            entity.CompanySerialNum = (int)dataReader["CompanySerialNum"];
            entity.CompanyName = (string)dataReader["CompanyName"];
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public CPSS.Data.DataAcess.DataModels.User.SigninUserDataModel Map(IDataReader dataReader)
	    {
			var result = new CPSS.Data.DataAcess.DataModels.User.SigninUserDataModel();
            result.UserID = (int)dataReader["UserID"];
            result.UserName = (string)dataReader["UserName"];
            result.CompanySerialNum = (int)dataReader["CompanySerialNum"];
            result.CompanyName = (string)dataReader["CompanyName"];
			return result;
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void MapObject(IDataReader dataReader, object entity)
	    {
	        this.Map(dataReader, entity as CPSS.Data.DataAcess.DataModels.User.SigninUserDataModel);
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public object MapObject(IDataReader dataReader)
	    {
	        return this.Map(dataReader);
	    }
	}
}
