//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;

namespace CPSS.Data.DataAccess
{
	/// <summary>
    /// 手动映射DataReader到SigninUserDataModel
    /// </summary>
    public partial class DataReaderToSigninUserDataModelMapper
    {
		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void Map(IDataReader dataReader, CPSS.Data.DataAcess.DataModels.User.SigninUserDataModel entity)
	    {            
            entity.userid = (int)dataReader["userid"];
            entity.username = (string)dataReader["username"];
            entity.comid = (int)dataReader["comid"];
            entity.comname = (string)dataReader["comname"];
            entity.ismanager = (bool)dataReader["ismanager"];
            entity.issystem = (bool)dataReader["issystem"];
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public CPSS.Data.DataAcess.DataModels.User.SigninUserDataModel Map(IDataReader dataReader)
	    {
			var result = new CPSS.Data.DataAcess.DataModels.User.SigninUserDataModel();
            result.userid = (int)dataReader["userid"];
            result.username = (string)dataReader["username"];
            result.comid = (int)dataReader["comid"];
            result.comname = (string)dataReader["comname"];
            result.ismanager = (bool)dataReader["ismanager"];
            result.issystem = (bool)dataReader["issystem"];
			return result;
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void MapObject(IDataReader dataReader, object entity)
	    {
	        this.Map(dataReader, entity as CPSS.Data.DataAcess.DataModels.User.SigninUserDataModel);
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public object MapObject(IDataReader dataReader)
	    {
	        return this.Map(dataReader);
	    }
	}
}
