//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;

namespace CPSS.Data.DataAccess
{
	/// <summary>
    /// 手动映射DataReader到UserDataModel
    /// </summary>
    public partial class DataReaderToUserDataModelMapper
    {
		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void Map(IDataReader dataReader, CPSS.Data.DataAcess.DataModels.SystemManage.UserManage.UserDataModel entity)
	    {            
            entity.UserId = (int)dataReader["UserId"];
            entity.ComId = (int)dataReader["ComId"];
            entity.EmpId = (int)dataReader["EmpId"];
            entity.UserName = (string)dataReader["UserName"];
            entity.UsePwd = (string)dataReader["UsePwd"];
            entity.Prefix = (string)dataReader["Prefix"];
            entity.Manager = (short)dataReader["Manager"];
            entity.Status = (short)dataReader["Status"];
            entity.Deleted = (short)dataReader["Deleted"];
            entity.Synchron = (short)dataReader["Synchron"];
            entity.CTime = (DateTime)dataReader["CTime"];
            entity.Comment = (string)dataReader["Comment"];
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public CPSS.Data.DataAcess.DataModels.SystemManage.UserManage.UserDataModel Map(IDataReader dataReader)
	    {
			var result = new CPSS.Data.DataAcess.DataModels.SystemManage.UserManage.UserDataModel();
            result.UserId = (int)dataReader["UserId"];
            result.ComId = (int)dataReader["ComId"];
            result.EmpId = (int)dataReader["EmpId"];
            result.UserName = (string)dataReader["UserName"];
            result.UsePwd = (string)dataReader["UsePwd"];
            result.Prefix = (string)dataReader["Prefix"];
            result.Manager = (short)dataReader["Manager"];
            result.Status = (short)dataReader["Status"];
            result.Deleted = (short)dataReader["Deleted"];
            result.Synchron = (short)dataReader["Synchron"];
            result.CTime = (DateTime)dataReader["CTime"];
            result.Comment = (string)dataReader["Comment"];
			return result;
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <param name="entity"></param>
		public void MapObject(IDataReader dataReader, object entity)
	    {
	        this.Map(dataReader, entity as CPSS.Data.DataAcess.DataModels.SystemManage.UserManage.UserDataModel);
	    }

		/// <summary>
        /// 映射
        /// </summary>
        /// <param name="dataReader"></param>
        /// <returns></returns>
	    public object MapObject(IDataReader dataReader)
	    {
	        return this.Map(dataReader);
	    }
	}
}
