//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSS.Data.DataAcess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDataModel
    {
        public int account_id { get; set; }
        public string class_id { get; set; }
        public string parent_id { get; set; }
        public int child_number { get; set; }
        public int child_count { get; set; }
        public string name { get; set; }
        public bool deleted { get; set; }
        public string alias { get; set; }
        public string serial_number { get; set; }
        public string Comment { get; set; }
        public decimal cur_total { get; set; }
        public decimal ini_total { get; set; }
        public string sysflag { get; set; }
        public bool sysrow { get; set; }
        public string PinYin { get; set; }
        public decimal total_01 { get; set; }
        public decimal total_02 { get; set; }
        public decimal total_03 { get; set; }
        public decimal total_04 { get; set; }
        public decimal total_05 { get; set; }
        public decimal total_06 { get; set; }
        public decimal total_07 { get; set; }
        public decimal total_08 { get; set; }
        public decimal total_09 { get; set; }
        public decimal total_10 { get; set; }
        public decimal total_11 { get; set; }
        public decimal total_12 { get; set; }
        public decimal bqtotal { get; set; }
        public decimal sumtotal { get; set; }
        public bool cashaudit { get; set; }
        public bool direction { get; set; }
        public byte[] ModifyDate { get; set; }
    }
}
