//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSS.Data.DataAcess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsDataModel
    {
        public int client_id { get; set; }
        public string class_id { get; set; }
        public string parent_id { get; set; }
        public int child_number { get; set; }
        public int child_count { get; set; }
        public string serial_number { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public Nullable<int> region_id { get; set; }
        public string phone_number { get; set; }
        public string address { get; set; }
        public string zipcode { get; set; }
        public string contact_personal { get; set; }
        public string tax_number { get; set; }
        public string acount_number { get; set; }
        public Nullable<double> credit_total { get; set; }
        public string pinyin { get; set; }
        public Nullable<short> pricemode { get; set; }
        public Nullable<short> sklimit { get; set; }
        public Nullable<double> artotal { get; set; }
        public Nullable<double> artotal_ini { get; set; }
        public Nullable<double> aptotal { get; set; }
        public Nullable<double> aptotal_ini { get; set; }
        public Nullable<double> pre_artotal { get; set; }
        public Nullable<double> pre_artotal_ini { get; set; }
        public Nullable<double> pre_aptotal { get; set; }
        public Nullable<double> pre_aptotal_ini { get; set; }
        public Nullable<bool> firstcheck { get; set; }
        public string comment { get; set; }
        public string csflag { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> ProtocolDate { get; set; }
        public byte[] ModifyDate { get; set; }
        public string GMPNo { get; set; }
        public string GSPNo { get; set; }
        public Nullable<byte> Cetype { get; set; }
        public int property { get; set; }
        public string comment1 { get; set; }
        public string comment2 { get; set; }
        public string comment3 { get; set; }
        public string comment4 { get; set; }
        public string comment5 { get; set; }
        public int RowIndex { get; set; }
        public int e_id { get; set; }
        public Nullable<bool> StopUse { get; set; }
        public decimal incrate { get; set; }
    }
}
