//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSS.Data.DataAcess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDataModel
    {
        public int company_id { get; set; }
        public string class_id { get; set; }
        public string parent_id { get; set; }
        public int child_number { get; set; }
        public int child_count { get; set; }
        public string serial_number { get; set; }
        public string name { get; set; }
        public bool deleted { get; set; }
        public string bank { get; set; }
        public string opaddress { get; set; }
        public string communicateaddr { get; set; }
        public string postcode { get; set; }
        public string tel { get; set; }
        public string manager { get; set; }
        public string email { get; set; }
        public string comment { get; set; }
        public bool StartUse { get; set; }
        public string prefix { get; set; }
        public short sklimit { get; set; }
        public short pricemode { get; set; }
        public string pinyin { get; set; }
        public byte[] ModifyDate { get; set; }
        public int RowIndex { get; set; }
        public Nullable<int> Area_ID { get; set; }
        public Nullable<int> businessStyle { get; set; }
    }
}
