//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSS.Data.DataAcess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesDataModel
    {
        public int emp_id { get; set; }
        public string class_id { get; set; }
        public string parent_id { get; set; }
        public int child_number { get; set; }
        public int child_count { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public string serial_number { get; set; }
        public Nullable<int> d_id { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string comment { get; set; }
        public Nullable<double> aplimit { get; set; }
        public Nullable<double> arlimit { get; set; }
        public Nullable<double> aptotal { get; set; }
        public Nullable<double> artotal { get; set; }
        public Nullable<decimal> discountlimit { get; set; }
        public Nullable<decimal> ls { get; set; }
        public Nullable<decimal> th { get; set; }
        public string pinyin { get; set; }
        public Nullable<double> LowPrice { get; set; }
        public Nullable<double> HighPrice { get; set; }
        public Nullable<int> SNCount { get; set; }
        public Nullable<int> GSPSNCount { get; set; }
        public byte[] ModifyDate { get; set; }
        public string Study { get; set; }
        public string Duty { get; set; }
        public Nullable<System.DateTime> GraduateDate { get; set; }
        public string szWork { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public string Teach { get; set; }
        public Nullable<double> deduct { get; set; }
        public byte[] lim { get; set; }
        public int Tp_ID { get; set; }
        public int RowIndex { get; set; }
    }
}
