//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSS.Data.DataAcess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class snstorageDataModel
    {
        public string sn { get; set; }
        public int subcomid { get; set; }
        public int stoid { get; set; }
        public int clientid { get; set; }
        public int empid { get; set; }
        public int depid { get; set; }
        public int proid { get; set; }
        public int billtype { get; set; }
        public int billid { get; set; }
        public Nullable<decimal> costprice { get; set; }
        public System.DateTime ctime { get; set; }
        public Nullable<System.DateTime> makedate { get; set; }
        public Nullable<System.DateTime> validdate { get; set; }
        public byte[] modifydate { get; set; }
    }
}
