//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSS.Data.DataAcess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class userDataModel
    {
        public int userid { get; set; }
        public int comid { get; set; }
        public Nullable<int> empid { get; set; }
        public string username { get; set; }
        public string usepwd { get; set; }
        public string prefix { get; set; }
        public short manager { get; set; }
        public short status { get; set; }
        public Nullable<short> deleted { get; set; }
        public short synchron { get; set; }
        public System.DateTime ctime { get; set; }
        public string comment { get; set; }
    }
}
