//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using CPSS.Common.Core.DataAccess.DataAccess;
using CPSS.Data.DataAccess.Interfaces;
using CPSS.Data.DataAcess.DataModels;

namespace CPSS.Data.DataAccess
{
	/// <summary>
    /// storage的数据访问层
    /// </summary>
	public partial class storageDataAccess : GenericDataAccessBase<storageDataModel>, IstorageDataAccess
	{
		/// <summary>
		/// 构造函数
		/// </summary>
		public storageDataAccess(IDbConnection connection) : base(connection)
        {
        }

		/// <summary>
		/// 根据编号获取storage
		/// </summary>
		public storageDataModel GetstorageDataModelById(int stoid)
		{
			this.ExecuteSQL = @"SELECT stoid,classid,parentid,childnumber,childcount,serialnumber,name,PinYin,alias,status,deleted,comment,sort From storage  WHERE  stoid = @stoid ";
			this.DataParameter = new DbParameter[]
			{
				new SqlParameter("@stoid", stoid),
			};
            return this.ExecuteReadSqlTostorageDataModel();
		}

		/// <summary>
		/// 新增
		/// </summary>
		public int Add(storageDataModel data, IDbTransaction tansaction)
	    {
            this.ExecuteSQL = @"INSERT INTO [storage] ([classid],[parentid],[childnumber],[childcount],[serialnumber],[name],[PinYin],[alias],[status],[deleted],[comment],[sort]) VALUES (@classid,@parentid,@childnumber,@childcount,@serialnumber,@name,@PinYin,@alias,@status,@deleted,@comment,@sort) 
 SELECT SCOPE_IDENTITY()";
			this.DataParameter = new DbParameter[]
            {
                new SqlParameter("@classid", data.classid),
                new SqlParameter("@parentid", data.parentid),
                new SqlParameter("@childnumber", data.childnumber),
                new SqlParameter("@childcount", data.childcount),
                new SqlParameter("@serialnumber", data.serialnumber),
                new SqlParameter("@name", data.name),
                new SqlParameter("@PinYin", data.PinYin),
                new SqlParameter("@alias", data.alias),
                new SqlParameter("@status", data.status),
                new SqlParameter("@deleted", data.deleted),
                new SqlParameter("@comment", data.comment),
                new SqlParameter("@sort", data.sort),
            };
	        return this.ExecuteNonQuery(tansaction, false);
	    }

		/// <summary>
		/// 新增
		/// </summary>
		public override int Add(storageDataModel data)
	    {
			return this.Add(data, null);
	    }

		/// <summary>
		/// 修改
		/// </summary>
		public int Update(storageDataModel data, IDbTransaction tansaction)
	    {
			this.ExecuteSQL = @"UPDATE storage SET  [classid] = @classid, [parentid] = @parentid, [childnumber] = @childnumber, [childcount] = @childcount, [serialnumber] = @serialnumber, [name] = @name, [PinYin] = @PinYin, [alias] = @alias, [status] = @status, [deleted] = @deleted, [comment] = @comment, [sort] = @sort WHERE  [stoid] = @stoid ";
			this.DataParameter = new DbParameter[]
            {
                new SqlParameter("@stoid", data.stoid),
                new SqlParameter("@classid", data.classid),
                new SqlParameter("@parentid", data.parentid),
                new SqlParameter("@childnumber", data.childnumber),
                new SqlParameter("@childcount", data.childcount),
                new SqlParameter("@serialnumber", data.serialnumber),
                new SqlParameter("@name", data.name),
                new SqlParameter("@PinYin", data.PinYin),
                new SqlParameter("@alias", data.alias),
                new SqlParameter("@status", data.status),
                new SqlParameter("@deleted", data.deleted),
                new SqlParameter("@comment", data.comment),
                new SqlParameter("@sort", data.sort),
            };
	        return this.ExecuteNonQuery(tansaction);
	    }

		/// <summary>
		/// 修改
		/// </summary>
		public override int Update(storageDataModel data)
	    {
			return this.Update(data, null);
	    }

		/// <summary>
		/// 删除
		/// </summary>
	    public int Delete(storageDataModel data, IDbTransaction tansaction)
	    {
			this.ExecuteSQL = @"DELETE FROM storage WHERE  [stoid] = @stoid ";
			this.DataParameter = new DbParameter[]
            {
                new SqlParameter("@stoid", data.stoid),
            };
	        return this.ExecuteNonQuery(tansaction);
	    }

		/// <summary>
		/// 删除
		/// </summary>
	    public override int Delete(storageDataModel data)
	    {
			return this.Delete(data, null);
	    }
	    
	}
}
