//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using CPSS.Common.Core.DataAccess.DataAccess;
using CPSS.Data.DataAccess.Interfaces;
using CPSS.Data.DataAcess.DataModels;

namespace CPSS.Data.DataAccess
{
	/// <summary>
    /// subcompany的数据访问层
    /// </summary>
	public partial class subcompanyDataAccess : GenericDataAccessBase<subcompanyDataModel>, IsubcompanyDataAccess
	{
		/// <summary>
		/// 构造函数
		/// </summary>
		public subcompanyDataAccess(IDbConnection connection) : base(connection)
        {
        }

		/// <summary>
		/// 根据编号获取subcompany
		/// </summary>
		public subcompanyDataModel GetsubcompanyDataModelById(int subcomid)
		{
			this.ExecuteSQL = @"SELECT subcomid,classid,parentid,childnumber,childcount,serialnumber,name,pinyin,pricemode,email,linkman,linktel,status,comment,sort,modifydate From subcompany  WHERE  subcomid = @subcomid ";
			this.DataParameter = new DbParameter[]
			{
				new SqlParameter("@subcomid", subcomid),                 
			};
            return this.ExecuteReadSqlTosubcompanyDataModel();
		}

		/// <summary>
		/// 新增
		/// </summary>
		public int Add(subcompanyDataModel data, IDbTransaction tansaction)
	    {
            this.ExecuteSQL = @"INSERT INTO [subcompany] ([classid],[parentid],[childnumber],[childcount],[serialnumber],[name],[pinyin],[pricemode],[email],[linkman],[linktel],[status],[comment],[sort],[modifydate]) VALUES (@classid,@parentid,@childnumber,@childcount,@serialnumber,@name,@pinyin,@pricemode,@email,@linkman,@linktel,@status,@comment,@sort,@modifydate) 
 SELECT SCOPE_IDENTITY()";
			this.DataParameter = new DbParameter[]
            {
                new SqlParameter("@classid", data.classid),                 
                new SqlParameter("@parentid", data.parentid),                 
                new SqlParameter("@childnumber", data.childnumber),                 
                new SqlParameter("@childcount", data.childcount),                 
                new SqlParameter("@serialnumber", data.serialnumber),                 
                new SqlParameter("@name", data.name),                 
                new SqlParameter("@pinyin", data.pinyin),                 
                new SqlParameter("@pricemode", data.pricemode),                 
                new SqlParameter("@email", data.email),                 
                new SqlParameter("@linkman", data.linkman),                 
                new SqlParameter("@linktel", data.linktel),                 
                new SqlParameter("@status", data.status),                 
                new SqlParameter("@comment", data.comment),                 
                new SqlParameter("@sort", data.sort),                 
                new SqlParameter("@modifydate", data.modifydate),                 
            };
	        return this.ExecuteNonQuery(tansaction, false);
	    }

		/// <summary>
		/// 新增
		/// </summary>
		public override int Add(subcompanyDataModel data)
	    {
			return this.Add(data, null);
	    }

		/// <summary>
		/// 修改
		/// </summary>
		public int Update(subcompanyDataModel data, IDbTransaction tansaction)
	    {
			this.ExecuteSQL = @"UPDATE subcompany SET  [classid] = @classid, [parentid] = @parentid, [childnumber] = @childnumber, [childcount] = @childcount, [serialnumber] = @serialnumber, [name] = @name, [pinyin] = @pinyin, [pricemode] = @pricemode, [email] = @email, [linkman] = @linkman, [linktel] = @linktel, [status] = @status, [comment] = @comment, [sort] = @sort, [modifydate] = @modifydate WHERE  [subcomid] = @subcomid ";
			this.DataParameter = new DbParameter[]
            {
                new SqlParameter("@subcomid", data.subcomid),                 
                new SqlParameter("@classid", data.classid),                 
                new SqlParameter("@parentid", data.parentid),                 
                new SqlParameter("@childnumber", data.childnumber),                 
                new SqlParameter("@childcount", data.childcount),                 
                new SqlParameter("@serialnumber", data.serialnumber),                 
                new SqlParameter("@name", data.name),                 
                new SqlParameter("@pinyin", data.pinyin),                 
                new SqlParameter("@pricemode", data.pricemode),                 
                new SqlParameter("@email", data.email),                 
                new SqlParameter("@linkman", data.linkman),                 
                new SqlParameter("@linktel", data.linktel),                 
                new SqlParameter("@status", data.status),                 
                new SqlParameter("@comment", data.comment),                 
                new SqlParameter("@sort", data.sort),                 
                new SqlParameter("@modifydate", data.modifydate),                 
            };
	        return this.ExecuteNonQuery(tansaction);
	    }

		/// <summary>
		/// 修改
		/// </summary>
		public override int Update(subcompanyDataModel data)
	    {
			return this.Update(data, null);
	    }

		/// <summary>
		/// 删除
		/// </summary>
	    public int Delete(subcompanyDataModel data, IDbTransaction tansaction)
	    {
			this.ExecuteSQL = @"DELETE FROM subcompany WHERE  [subcomid] = @subcomid ";
			this.DataParameter = new DbParameter[]
            {
                new SqlParameter("@subcomid", data.subcomid),                 
            };
	        return this.ExecuteNonQuery(tansaction);
	    }

		/// <summary>
		/// 删除
		/// </summary>
	    public override int Delete(subcompanyDataModel data)
	    {
			return this.Delete(data, null);
	    }
	    
	}
}
