USE CPSSMASTER
GO
IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE id=OBJECT_ID(N'[dbo].[syscompany]') AND OBJECTPROPERTY(id,N'IsUserTable')=1)
BEGIN
	DROP TABLE [dbo].[syscompany]
END
GO
CREATE TABLE [dbo].[syscompany](	
	[comid] INT IDENTITY(1,1) NOT NULL,
	[comname] VARCHAR(128) NOT NULL,
	[linkemail] VARCHAR(30) NOT NULL,
	[linkman] VARCHAR(20) NOT NULL,
	[linktel] VARCHAR(60) NOT NULL,
	[status] SMALLINT NOT NULL,
	[sortindex] INT NOT NULL,
	[comment] VARCHAR(100) NULL DEFAULT(''),
	[modifydate] TIMESTAMP NULL,
	CONSTRAINT [PK_syscompany_comid] PRIMARY KEY CLUSTERED 
	(
		[comid] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 99) ON [PRIMARY]
) ON [PRIMARY]
GO